//TESTING
export const GET_STORES = "[TESTING] GET_STORES";

//SESSION
export const CHECK_SESSION = "[AUTH] CHECK_SESSION";

//LOGIN
export const OPEN_LOGIN_MODAL = "[UI] OPEN_LOGIN_MODAL";
export const HANDLE_AUTHENTICATION = "[AUTH] HANDLE_AUTHENTICATION";
export const RECIEVE_USER_DATA = "[AUTH] RECIEVE_USER_DATA";
export const AUTH_SUCCESS = "[AUTH] AUTH_SUCCESS";
export const AUTH_FAILED = "[AUTH] AUTH_FAILED";
export const CLOSE_LOGIN_MODAL = "[UI] CLOSE_LOGIN_MODAL";

//REGISTER
export const OPEN_REGISTER_MODAL = "[UI] OPEN_REGISTER_MODAL";
export const HANDLE_REGISTRATION = "[UI] HANDLE_REGISTRATION";
export const CLOSE_REGISTER_MODAL = "[UI] CLOSE_REGISTER_MODAL";

//MOBILE DRAWER
export const OPEN_MOBILE_DRAWER = "[UI] OPEN_MOBILE_DRAWER";
export const CLOSE_MOBILE_DRAWER = "[UI] CLOSE_MOBILE_DRAWER";

//HELP DRAWER
export const OPEN_HELP_DRAWER = "[UI] OPEN_HELP_DRAWER";
export const CLOSE_HELP_DRAWER = "[UI] CLOSE_HELP_DRAWER";

//SHOPPING CART
export const ADD_TO_CART = "[CART] ADD_TO_CART";
export const REMOVE_FROM_CART = "[CART] REMOVE_FROM_CART";
export const CANCEL_CART = "[CART] CANCEL_CART";

//MESSAGES
export const NEW_MESSAGE_MODAL_OPEN = "[UI] NEW_MESSAGE_MODAL_OPEN";
export const NEW_MESSAGE = "[WEBSOCKET] NEW_MESSAGE";
export const SELECT_MESSAGE = "[DATA] SELECT_MESSAGE";
export const UPDATE_MESSENGER = "[DATA] UPDATE_MESSENGER";
export const NEW_MESSAGE_MODAL_CLOSE = "[UI] NEW_MESSAGE_MODAL_CLOSE";

//CONNECTIONS
export const GET_CONNECTIONS = "[DATA] GET_CONNECTIONS";
export const RECIEVE_CONNECTIONS = "[DATA] RECIEVE_CONNECTIONS";
export const UPDATE_MESSAGES = "[DATA] UPDATE_MESSAGES";

//MESSAGES
//WEBSOCKET
export const START_CHANNEL = "[WEBSOCKET] START_CHANNEL";
export const STOP_CHANNEL = "[WEBSOCKET] STOP_CHANNEL";
export const CHANNEL_ON = "[WEBSOCKET] CHANNEL_ON";
export const CHANNEL_OFF = "[WEBSOCKET] CHANNEL_OFF";
export const SERVER_ON = "[WEBSOCKET] SERVER_ON";
export const SERVER_OFF = "[WEBSOCKET] SERVER_OFF";
export const SEND_MESSAGE = "[WEBSOCKET] SEND_MESSAGE";
